//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chauffeur.Console.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IChauffeurService")]
    public interface IChauffeurService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChauffeurService/InstallLastSuccessfulBuild", ReplyAction="http://tempuri.org/IChauffeurService/InstallLastSuccessfulBuildResponse")]
        Chauffeur.Jenkins.Model.Build InstallLastSuccessfulBuild(string jobName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChauffeurService/InstallLastSuccessfulBuild", ReplyAction="http://tempuri.org/IChauffeurService/InstallLastSuccessfulBuildResponse")]
        System.Threading.Tasks.Task<Chauffeur.Jenkins.Model.Build> InstallLastSuccessfulBuildAsync(string jobName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IChauffeurServiceChannel : Chauffeur.Console.ServiceReference.IChauffeurService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ChauffeurServiceClient : System.ServiceModel.ClientBase<Chauffeur.Console.ServiceReference.IChauffeurService>, Chauffeur.Console.ServiceReference.IChauffeurService {
        
        public ChauffeurServiceClient() {
        }
        
        public ChauffeurServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ChauffeurServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChauffeurServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChauffeurServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Chauffeur.Jenkins.Model.Build InstallLastSuccessfulBuild(string jobName) {
            return base.Channel.InstallLastSuccessfulBuild(jobName);
        }
        
        public System.Threading.Tasks.Task<Chauffeur.Jenkins.Model.Build> InstallLastSuccessfulBuildAsync(string jobName) {
            return base.Channel.InstallLastSuccessfulBuildAsync(jobName);
        }
    }
}
